# Generated by Django 3.1.7 on 2021-09-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rental',
            table='rentals',
        ),
    ]
