# Generated by Django 3.2.6 on 2021-09-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
