# Generated by Django 3.1.5 on 2021-09-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarStat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'carstat',
            },
        ),
        migrations.CreateModel(
            name='OfficeStat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'officestat',
            },
        ),
    ]
