# Generated by Django 3.1.7 on 2021-08-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('carUid', models.UUIDField()),
                ('brand', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('power', models.IntegerField()),
                ('car_type', models.CharField(max_length=255)),
                ('price_per_hour', models.FloatField()),
            ],
        ),
    ]
