# Generated by Django 3.1.7 on 2021-09-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='cars',
        ),
    ]
