# Generated by Django 3.1.7 on 2021-09-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rent_uid', models.UUIDField()),
                ('status', models.CharField(max_length=16)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
